### ISSUE TITLE
matplotlib.tight_layout restricts matplotlib version to 3.5.2

### ISSUE THREAD

**Issue by ilibarra** [jnothman/UpSetPlot#191]
Dear UpSetPlot team,

On an issue related to matplotlib in this repository, I am asking whether this dependency limitation of matplotlib to version 3.5.2 can be considered and fixed to handle matplotlib >=3.6
https://github.com/theislab/superexacttestpy/issues/18

Thank you,

**Comment by 0xharib** [comment]
I am not able to get it to work with even matplotlib==3.5.2 - does this work for you @ilibarra?

**Comment by jbloom** [comment]
I also run into an error on `matplotlib` 3.6:
```
from matplotlib.tight_layout import get_renderer
ImportError: cannot import name 'get_renderer' from 'matplotlib.tight_layout'
```

**Comment by andrewjkwok** [comment]
Hello - I am getting the exact same error with matplotlib 3.6.1.

```
import upsetplot
ImportError: cannot import name 'get_renderer' from 'matplotlib.tight_layout'
```

**Comment by jbloom** [comment]
@jnothman, is there any chance of getting this merged?

**Comment by nateharms** [comment]
Hi there! Any progress on #192? I'm running into the same issue as well

**Comment by jnothman** [comment]
Fixed in #192
